[I 2024-12-04 11:55:16,442] A new study created in RDB with name: Vc_rf
[I 2024-12-04 11:55:25,119] Trial 0 finished with value: 0.5872497852420174 and parameters: {'n_estimators': 117, 'max_depth': 12, 'min_samples_split': 23, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': False, 'criterion': 'squared_error'}. Best is trial 0 with value: 0.5872497852420174.
[I 2024-12-04 11:55:25,755] Trial 3 finished with value: 0.6864521614755885 and parameters: {'n_estimators': 742, 'max_depth': 36, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'squared_error'}. Best is trial 0 with value: 0.5872497852420174.
[I 2024-12-04 11:55:26,842] Trial 11 finished with value: 1.2075926252014746 and parameters: {'n_estimators': 856, 'max_depth': 26, 'min_samples_split': 12, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'squared_error'}. Best is trial 0 with value: 0.5872497852420174.
[I 2024-12-04 11:55:31,806] Trial 14 finished with value: 1.2377361796312913 and parameters: {'n_estimators': 218, 'max_depth': 27, 'min_samples_split': 22, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'squared_error'}. Best is trial 0 with value: 0.5872497852420174.
[I 2024-12-04 11:55:31,817] Trial 8 finished with value: 1.1716186474665577 and parameters: {'n_estimators': 793, 'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 0 with value: 0.5872497852420174.
[W 2024-12-04 11:55:32,836] Trial 13 failed with parameters: {'n_estimators': 294, 'max_depth': 35, 'min_samples_split': 3} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 81, in _create_scoped_session
    session.commit()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trial_params (trial_id, param_name, param_value, distribution_json) VALUES (?, ?, ?, ?)]
[parameters: (14, 'min_samples_leaf', 2.0, '{"name": "IntDistribution", "attributes": {"log": true, "step": 1, "low": 1, "high": 15}}')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 242, in objective
    params = {
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 243, in <dictcomp>
    name: suggest_fn(trial, name)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 164, in <lambda>
    return lambda trial, name: trial.suggest_int(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/_convert_positional_args.py", line 83, in converter_wrapper
    return func(**kwargs)  # type: ignore[call-arg]
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 324, in suggest_int
    suggested_value = int(self._suggest(name, distribution))
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 585, in set_trial_param
    self._set_trial_param_without_commit(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 98, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2024-12-04 11:55:32,975] Trial 13 failed with value None.
[I 2024-12-04 11:55:35,121] Trial 4 finished with value: 0.5771567546434403 and parameters: {'n_estimators': 784, 'max_depth': 43, 'min_samples_split': 22, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': False, 'criterion': 'squared_error'}. Best is trial 4 with value: 0.5771567546434403.
[I 2024-12-04 11:55:35,341] Trial 30 finished with value: 0.8688570749076928 and parameters: {'n_estimators': 230, 'max_depth': 34, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'absolute_error'}. Best is trial 4 with value: 0.5771567546434403.
[I 2024-12-04 11:55:36,833] Trial 26 finished with value: 1.33016281713803 and parameters: {'n_estimators': 106, 'max_depth': 27, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'absolute_error'}. Best is trial 4 with value: 0.5771567546434403.
[I 2024-12-04 11:55:37,412] Trial 9 finished with value: 1.2439118410553112 and parameters: {'n_estimators': 149, 'max_depth': 22, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'absolute_error'}. Best is trial 4 with value: 0.5771567546434403.
[I 2024-12-04 11:55:38,640] Trial 1 finished with value: 1.2583792732246915 and parameters: {'n_estimators': 812, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 4 with value: 0.5771567546434403.
[I 2024-12-04 11:55:39,562] Trial 19 finished with value: 1.2024045170068813 and parameters: {'n_estimators': 473, 'max_depth': 47, 'min_samples_split': 24, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 4 with value: 0.5771567546434403.
[I 2024-12-04 11:55:41,697] Trial 22 finished with value: 0.6691240095335154 and parameters: {'n_estimators': 461, 'max_depth': 39, 'min_samples_split': 15, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'absolute_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:42,714] Trial 23 finished with value: 0.8492851862993104 and parameters: {'n_estimators': 766, 'max_depth': 42, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:42,719] Trial 7 finished with value: 0.5366157915572876 and parameters: {'n_estimators': 839, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:42,769] Trial 25 finished with value: 0.4974047815457257 and parameters: {'n_estimators': 462, 'max_depth': 43, 'min_samples_split': 17, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:43,466] Trial 29 finished with value: 1.3374782688544629 and parameters: {'n_estimators': 844, 'max_depth': 15, 'min_samples_split': 48, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'absolute_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:43,615] Trial 21 finished with value: 0.5294251232579529 and parameters: {'n_estimators': 355, 'max_depth': 26, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': True, 'criterion': 'absolute_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:43,992] Trial 27 finished with value: 0.6078222324406071 and parameters: {'n_estimators': 925, 'max_depth': 27, 'min_samples_split': 26, 'min_samples_leaf': 12, 'max_features': None, 'bootstrap': False, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:44,053] Trial 6 finished with value: 1.1635990677065913 and parameters: {'n_estimators': 531, 'max_depth': 42, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:44,977] Trial 16 finished with value: 0.9683816795306434 and parameters: {'n_estimators': 612, 'max_depth': 50, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'absolute_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:45,241] Trial 24 finished with value: 1.3044017589365113 and parameters: {'n_estimators': 487, 'max_depth': 23, 'min_samples_split': 5, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'absolute_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:47,126] Trial 2 finished with value: 1.2554875106608354 and parameters: {'n_estimators': 659, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:48,425] Trial 33 finished with value: 1.2338711819816357 and parameters: {'n_estimators': 777, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:49,636] Trial 28 finished with value: 0.5419229051029403 and parameters: {'n_estimators': 999, 'max_depth': 16, 'min_samples_split': 18, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': False, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:50,423] Trial 34 finished with value: 0.8260008181425974 and parameters: {'n_estimators': 646, 'max_depth': 39, 'min_samples_split': 16, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:51,812] Trial 36 finished with value: 0.5902252202062596 and parameters: {'n_estimators': 507, 'max_depth': 39, 'min_samples_split': 24, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:51,817] Trial 18 finished with value: 0.622700292495473 and parameters: {'n_estimators': 805, 'max_depth': 44, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'absolute_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:51,933] Trial 35 finished with value: 0.6237174088143865 and parameters: {'n_estimators': 459, 'max_depth': 39, 'min_samples_split': 29, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:52,679] Trial 12 finished with value: 1.1325182655800108 and parameters: {'n_estimators': 951, 'max_depth': 45, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'absolute_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:52,875] Trial 5 finished with value: 0.6706193859295178 and parameters: {'n_estimators': 775, 'max_depth': 14, 'min_samples_split': 29, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': True, 'criterion': 'absolute_error'}. Best is trial 25 with value: 0.4974047815457257.
[I 2024-12-04 11:55:53,410] Trial 32 finished with value: 0.49410487476698517 and parameters: {'n_estimators': 863, 'max_depth': 21, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': True, 'criterion': 'squared_error'}. Best is trial 32 with value: 0.49410487476698517.
[I 2024-12-04 11:55:58,689] Trial 31 finished with value: 0.6149584918383392 and parameters: {'n_estimators': 645, 'max_depth': 44, 'min_samples_split': 46, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': False, 'criterion': 'absolute_error'}. Best is trial 32 with value: 0.49410487476698517.
[I 2024-12-04 11:56:04,811] Trial 10 finished with value: 0.4866821794844203 and parameters: {'n_estimators': 679, 'max_depth': 36, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': True, 'criterion': 'absolute_error'}. Best is trial 10 with value: 0.4866821794844203.
[I 2024-12-04 11:56:14,538] Trial 17 finished with value: 0.45045142212342193 and parameters: {'n_estimators': 623, 'max_depth': 35, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True, 'criterion': 'absolute_error'}. Best is trial 17 with value: 0.45045142212342193.
[I 2024-12-04 11:56:19,600] Trial 15 finished with value: 0.5762776859009829 and parameters: {'n_estimators': 746, 'max_depth': 17, 'min_samples_split': 28, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False, 'criterion': 'absolute_error'}. Best is trial 17 with value: 0.45045142212342193.
[I 2024-12-04 11:57:09,230] Trial 20 finished with value: 0.4252751644953182 and parameters: {'n_estimators': 680, 'max_depth': 40, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': False, 'criterion': 'absolute_error'}. Best is trial 20 with value: 0.4252751644953182.
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 81, in _create_scoped_session
    session.commit()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trial_params (trial_id, param_name, param_value, distribution_json) VALUES (?, ?, ?, ?)]
[parameters: (14, 'min_samples_leaf', 2.0, '{"name": "IntDistribution", "attributes": {"log": true, "step": 1, "low": 1, "high": 15}}')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/Documents/fair_gc/gc_ml.py", line 79, in <module>
    study, best_model = create_hyperparameter_optimizer(
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 275, in create_hyperparameter_optimizer
    study.optimize(objective, n_trials=n_trials, n_jobs=n_jobs)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 100, in _optimize
    f.result()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 242, in objective
    params = {
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 243, in <dictcomp>
    name: suggest_fn(trial, name)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 164, in <lambda>
    return lambda trial, name: trial.suggest_int(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/_convert_positional_args.py", line 83, in converter_wrapper
    return func(**kwargs)  # type: ignore[call-arg]
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 324, in suggest_int
    suggested_value = int(self._suggest(name, distribution))
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 585, in set_trial_param
    self._set_trial_param_without_commit(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 98, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
